import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, '../frontend/src/data');

// Dynamic imports of data modules
const { ENN_BASE } = await import(join(dataDir, 'ennBase.js'));
const { MBTI_MODIFIERS } = await import(join(dataDir, 'mbtiModifiers.js'));
const { INST_MODIFIERS } = await import(join(dataDir, 'instModifiers.js'));
const { CROSS_RULES, findCrossRule } = await import(join(dataDir, 'crossRules.js'));

const ENN_TYPES = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const WINGS = {
  1: [9, 2], 2: [1, 3], 3: [2, 4], 4: [3, 5], 5: [4, 6],
  6: [5, 7], 7: [6, 8], 8: [7, 9], 9: [8, 1]
};
const MBTI_LIST = ['INFP', 'INFJ', 'INTP', 'INTJ', 'ENFP', 'ENFJ', 'ENTP', 'ENTJ', 'ISFP', 'ISFJ', 'ISTP', 'ISTJ', 'ESFP', 'ESFJ', 'ESTP', 'ESTJ'];
const INST_STACKS = ['SP/SX/SO', 'SP/SO/SX', 'SX/SP/SO', 'SX/SO/SP', 'SO/SP/SX', 'SO/SX/SP'];

function assembleCombination(ennType, wing, mbtiType, instStack) {
  const ennKey = `${ennType}w${wing}`;
  const ennBase = ENN_BASE[ennKey] || {};
  const mbtiMod = MBTI_MODIFIERS[mbtiType] || {};
  const instMod = INST_MODIFIERS[instStack] || {};

  const crossRules = findCrossRule({ ennType: String(ennType), mbtiType, instStack });
  const ennMbtiRule = crossRules.find(r => r.type === 'enn_mbti');
  const ennInstRule = crossRules.find(r => r.type === 'enn_inst');
  const mbtiInstRule = crossRules.find(r => r.type === 'mbti_inst');

  // Compose portrait from layers
  const portrait = [
    ennBase.portrait || '',
    mbtiMod.cognitivePortrait || '',
    instMod.relationalFocus || '',
  ].filter(Boolean).join(' ');

  const strengths = [
    ...(ennBase.strengths || []),
    mbtiMod.workStyle ? mbtiMod.workStyle.split('.')[0] : '',
  ].filter(Boolean).slice(0, 5);

  const growthEdges = [
    ...(ennBase.growthEdges || []),
    instMod.blindSpot || '',
  ].filter(Boolean).slice(0, 4);

  const inRelationships = [
    instMod.relationalFocus || '',
    ennMbtiRule?.synergy || '',
  ].filter(Boolean).join(' ');

  const atWork = [
    mbtiMod.workStyle || '',
    instMod.energyPattern || '',
  ].filter(Boolean).join(' ');

  const notes = [
    ennMbtiRule?.tension || '',
    ennInstRule?.synergy || '',
    mbtiInstRule?.tension || '',
  ].filter(Boolean);

  return {
    ennType,
    wing,
    mbtiType,
    instStack,
    portrait: portrait.trim(),
    strengths,
    growthEdges,
    inRelationships: inRelationships.trim(),
    atWork: atWork.trim(),
    stressBehavior: [ennBase.stressSummary, mbtiMod.stressGrip].filter(Boolean).join(' '),
    growthPath: ennBase.growthSummary || '',
    notes,
  };
}

// Generate all 1,728 combinations
const profiles = {};
for (const ennType of ENN_TYPES) {
  for (const wing of WINGS[ennType]) {
    for (const mbtiType of MBTI_LIST) {
      for (const instStack of INST_STACKS) {
        const key = `${ennType}w${wing}_${mbtiType}_${instStack.replace(/\//g, '')}`;
        profiles[key] = assembleCombination(ennType, wing, mbtiType, instStack);
      }
    }
  }
}

const output = `// Auto-generated by scripts/generateCombinations.mjs — do not hand-edit\n// ${Object.keys(profiles).length} profiles total\nexport const COMBINATION_PROFILES = ${JSON.stringify(profiles, null, 2)};\n`;

const outPath = join(dataDir, 'combinationProfiles.js');
writeFileSync(outPath, output, 'utf-8');
console.log(`Written ${Object.keys(profiles).length} profiles to ${outPath}`);
const sizeKB = Math.round(Buffer.byteLength(output) / 1024);
console.log(`File size: ${sizeKB} KB`);
if (sizeKB > 1024) {
  console.warn('WARNING: File exceeds 1MB — consider lazy loading strategy');
}
