/**
 * Splits combinationProfiles.js into per-wing modules for lazy loading.
 *
 * The wing files were checked in as "auto-generated" without a generator, so
 * they could not be kept in step with the monolith. This is that generator.
 * Run it after generateCombinations.mjs.
 */
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, '../frontend/src/data');
const outDir = join(dataDir, 'combinations');

const { COMBINATION_PROFILES } = await import(join(dataDir, 'combinationProfiles.js'));

const byWing = {};
for (const [key, profile] of Object.entries(COMBINATION_PROFILES)) {
  const wingKey = key.split('_')[0];
  (byWing[wingKey] ??= {})[key] = profile;
}

let total = 0;
for (const [wingKey, profiles] of Object.entries(byWing)) {
  // Minified, matching how these files were already checked in: they are the
  // lazy-loaded chunks, so the whitespace would be shipped to the browser.
  const body = `// Auto-generated by scripts/splitCombinations.mjs — do not hand-edit. Wing: ${wingKey}\n`
    + `export const PROFILES_${wingKey} = ${JSON.stringify(profiles)};\n`;
  writeFileSync(join(outDir, `${wingKey}.js`), body, 'utf-8');
  total += Object.keys(profiles).length;
}

console.log(`Written ${Object.keys(byWing).length} wing files, ${total} profiles total`);
